### ISSUE TITLE
Downgrade screen resolution driver from 1080 x 2160 to 800 x 1600 

### ISSUE THREAD

**Issue by proganime1200** [Blacksuan19/kernel_dark_ages_vince#14]
Just like all other phones our sd 625 needs a lightweight screen resolution compare it to redmi 7 or any pones with entry level or mid for battery and less intesnsive processing

**Comment by CloudedQuartz** [comment]
Are u fr

**Comment by proganime1200** [comment]
> Are u fr

uhm whats wrong requesting for a feature ? i see many had implemented this so this is possible or you can just close if you didnt want it though XD

**Comment by danascape** [comment]
Nigga

**Comment by yiesko** [comment]
lmao

**Comment by 00day0** [comment]
Lmao

**Comment by SALMANKHANPM** [comment]
hmm

**Comment by Rasenkai** [comment]
Pro

**Comment by henricaodopao** [comment]
bruh

**Comment by uditkarode** [comment]
Downgrade to 9x16, infinite battery

**Comment by ender1324** [comment]
I recommend downgrading to 480x1000 for best performance

**Comment by Blacksuan19** [comment]
Bruh

**Comment by Blacksuan19** [comment]
Somebody get this on gitretards

**Comment by Ramisky** [comment]
> I recommend downgrading to 480x1000 for best performance

Yes, tested and works
