### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by nios34** [Blacksuan19/kernel_dark_ages_vince#4]
In file included from drivers/net/ethernet/msm/rndis_ipa_trace.h:81:0,
                 from drivers/net/ethernet/msm/rndis_ipa.c:32:
include/trace/define_trace.h:83:43: fatal error: ./rndis_ipa_trace.h: No such file or directory
 #include TRACE_INCLUDE(TRACE_INCLUDE_FILE)
                                           ^
compilation terminated.
make[4]: *** [scripts/Makefile.build:272：drivers/net/ethernet/msm/rndis_ipa.o] 错误 1
make[3]: *** [scripts/Makefile.build:416：drivers/net/ethernet/msm] 错误 2
make[2]: *** [scripts/Makefile.build:416：drivers/net/ethernet] 错误 2
make[1]: *** [scripts/Makefile.build:416：drivers/net] 错误 2
make: *** [Makefile:1014：drivers] 错误 2

How to fix it?

**Comment by nios34** [comment]
ln rndis_ipa_trace.h to include/trace/ ?

**Comment by Blacksuan19** [comment]
can you give more details like branch and toolchain used and your build commands/scrips?

**Comment by nios34** [comment]
Yes

**Comment by nios34** [comment]
Branch: darkly-beta
Phone: vince
Toolchain: aarch64-linux-android-4.9

Command:
make menuconfig #I want build a kernel for nethunter
make -j 5

**Comment by nios34** [comment]
Do you need my kernel config?

**Comment by nios34** [comment]
I fixed it but There are many similar errors

**Comment by ramabondanp** [comment]
> Branch: darkly-beta
> Phone: vince
> Toolchain: aarch64-linux-android-4.9
> 
> Command:
> make menuconfig #I want build a kernel for nethunter
> make -j 5

dont build on root
use O=out option

**Comment by nios34** [comment]
If i use " O=out option " My config will dosen't work

**Comment by Blacksuan19** [comment]
Use the build script included in the source 
Just change defconfig string
